[bin]
get_novel=/usr/local/bin/get_novel.pl
send_email=/usr/bin/calibre-smtp

[site]
mail="mail.myebookserver.com"
web="myebookserver.com"
web_path=/var/www/html/ebook
bare_pwd='some_pwd_xxx'

[mail]
args=' -M smtp.gmail.com -p 587 -U xxxxx\@gmail.com -P xxxxxxxxxxxxxxxx -F xxxxx@gmail.com '

[mailbox]
default_recv='somekindleusr@kindle.cn'
default_send='kindle@myebookserver.com'
 
[db]  
usr=mydbusr
pwd=mydbpwd
host=localhost
#mysql='mysql://mydbusr:mydbpwd@localhost/minion'

[ebook]
type='epub'
